<script setup lang="ts">
import { ref } from 'vue'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Separator } from '@/components/ui/separator'

// Local state for the UI toggles
const streamResponses = ref(true)
const compactMode = ref(false)
const selectedTheme = ref('midnight')

const themes = [
  { id: 'midnight', label: 'Midnight', class: 'bg-zinc-950 border-2 border-primary text-zinc-50' },
  { id: 'paper', label: 'Paper', class: 'bg-zinc-100 border border-border text-zinc-900 hover:border-primary/50' },
  { id: 'deep-sea', label: 'Deep Sea', class: 'bg-slate-900 border border-border text-slate-50 hover:border-primary/50' },
]
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Appearance & Behavior</CardTitle>
      <CardDescription>Customize how Candlekeep looks and feels.</CardDescription>
    </CardHeader>
    <CardContent class="space-y-6">
      <div class="flex items-center justify-between">
        <div class="space-y-0.5">
          <Label class="text-base">Stream Responses</Label>
          <p class="text-sm text-muted-foreground">
            Show text as it is being generated by the LLM.
          </p>
        </div>
        <Switch v-model="streamResponses" />
      </div>

      <Separator />

      <div class="flex items-center justify-between">
        <div class="space-y-0.5">
          <Label class="text-base">Compact Mode</Label>
          <p class="text-sm text-muted-foreground">
            Reduce padding and font sizes for high-density displays.
          </p>
        </div>
        <Switch v-model="compactMode" />
      </div>

      <Separator />

      <div class="space-y-3">
        <Label>Theme Preset</Label>
        <div class="grid grid-cols-3 gap-4">
          <div
            v-for="theme in themes"
            :key="theme.id"
            @click="selectedTheme = theme.id"
            :class="[
               'h-20 rounded-md cursor-pointer flex items-center justify-center font-medium transition-all',
               theme.class,
               selectedTheme === theme.id ? 'ring-2 ring-primary ring-offset-2' : ''
             ]"
          >
            {{ theme.label }}
          </div>
        </div>
      </div>
    </CardContent>
  </Card>
</template>
